CREATE TABLE Documents (
    UUID UNIQUEIDENTIFIER PRIMARY KEY,
    CreationDate DATETIME NOT NULL,
    CustomerUUID UNIQUEIDENTIFIER NOT NULL,
    Comment NVARCHAR(MAX)
);

ALTER TABLE Documents
ADD Name NVARCHAR(255),
    Number BIGINT;
