CREATE TABLE Insurances (
    UUID UNIQUEIDENTIFIER PRIMARY KEY,
    PawnedItemUUID UNIQUEIDENTIFIER NOT NULL,
    InsuranceAmount DECIMAL(18, 2) NOT NULL,
    InsuranceDate DATETIME NOT NULL,
    FOREIGN KEY (PawnedItemUUID) REFERENCES PawnedItems(UUID),
);