CREATE TABLE PawnedItems (
    UUID UNIQUEIDENTIFIER PRIMARY KEY,
    LoanUUID UNIQUEIDENTIFIER NOT NULL,
    Description NVARCHAR(255) NOT NULL,
    EstimatedValue DECIMAL(18, 2) NOT NULL,
    PawnDate DATETIME NOT NULL,
    ExpiryDate DATETIME NOT NULL,
    IsSold BIT NOT NULL,
    FOREIGN KEY (LoanUUID) REFERENCES Loans(UUID)
);