CREATE TABLE Payments (
    UUID UNIQUEIDENTIFIER PRIMARY KEY,
    LoanUUID UNIQUEIDENTIFIER NOT NULL,
    PaymentAmount DECIMAL(18, 2),
    PaymentDate DATETIME,
    CONSTRAINT FK_Payments_Loans FOREIGN KEY (LoanUUID) REFERENCES Loans(UUID)
);