CREATE TABLE Sales (
    UUID UNIQUEIDENTIFIER PRIMARY KEY,
    PawnedItemUUID UNIQUEIDENTIFIER NOT NULL,
    SaleAmount DECIMAL(18, 2) NOT NULL,
    SaleDate DATETIME NOT NULL,
    FOREIGN KEY (PawnedItemUUID) REFERENCES PawnedItems(UUID)
);